drop extension if exists "pg_net";


  create table "public"."message" (
    "id" uuid not null default gen_random_uuid(),
    "timestamp" timestamp with time zone not null default now(),
    "message" text,
    "user_id" uuid,
    "message_session_id" uuid
      );



  create table "public"."message_session" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "organization_id" uuid,
    "title" character varying,
    "last_message_sent" text
      );



  create table "public"."message_session_users" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "message_session" uuid,
    "user_id" uuid,
    "unread_messages" bigint
      );



  create table "public"."organization" (
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "description" text,
    "id" uuid not null default gen_random_uuid()
      );



  create table "public"."organization_members" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "organization_id" uuid,
    "user_id" uuid,
    "role" text
      );



  create table "public"."profiles" (
    "id" uuid not null,
    "full_name" text,
    "avatar_url" text
      );


CREATE UNIQUE INDEX "MessageSessionUsers_pkey" ON public.message_session_users USING btree (id);

CREATE UNIQUE INDEX "MessageSession_pkey" ON public.message_session USING btree (id);

CREATE UNIQUE INDEX message_pkey ON public.message USING btree (id);

CREATE UNIQUE INDEX organization_members_pkey ON public.organization_members USING btree (id);

CREATE UNIQUE INDEX organization_pkey ON public.organization USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."message" add constraint "message_pkey" PRIMARY KEY using index "message_pkey";

alter table "public"."message_session" add constraint "MessageSession_pkey" PRIMARY KEY using index "MessageSession_pkey";

alter table "public"."message_session_users" add constraint "MessageSessionUsers_pkey" PRIMARY KEY using index "MessageSessionUsers_pkey";

alter table "public"."organization" add constraint "organization_pkey" PRIMARY KEY using index "organization_pkey";

alter table "public"."organization_members" add constraint "organization_members_pkey" PRIMARY KEY using index "organization_members_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."message" add constraint "message_session_fkey" FOREIGN KEY (message_session_id) REFERENCES public.message_session(id) not valid;

alter table "public"."message" validate constraint "message_session_fkey";

alter table "public"."message" add constraint "message_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."message" validate constraint "message_user_id_fkey";

alter table "public"."message" add constraint "message_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."message" validate constraint "message_user_id_fkey1";

alter table "public"."message_session" add constraint "MessageSession_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organization(id) not valid;

alter table "public"."message_session" validate constraint "MessageSession_organization_id_fkey";

alter table "public"."message_session_users" add constraint "MessageSessionUsers_message_session_fkey" FOREIGN KEY (message_session) REFERENCES public.message_session(id) not valid;

alter table "public"."message_session_users" validate constraint "MessageSessionUsers_message_session_fkey";

alter table "public"."message_session_users" add constraint "MessageSessionUsers_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."message_session_users" validate constraint "MessageSessionUsers_user_id_fkey";

alter table "public"."organization_members" add constraint "organization_members_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES public.organization(id) not valid;

alter table "public"."organization_members" validate constraint "organization_members_organization_id_fkey";

alter table "public"."organization_members" add constraint "organization_members_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."organization_members" validate constraint "organization_members_user_id_fkey";

alter table "public"."organization_members" add constraint "organization_members_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."organization_members" validate constraint "organization_members_user_id_fkey1";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  insert into profiles (id, full_name)
  values (new.id, new.user_metadata->>'full_name');
  return new;
end;
$function$
;

grant delete on table "public"."message" to "anon";

grant insert on table "public"."message" to "anon";

grant references on table "public"."message" to "anon";

grant select on table "public"."message" to "anon";

grant trigger on table "public"."message" to "anon";

grant truncate on table "public"."message" to "anon";

grant update on table "public"."message" to "anon";

grant delete on table "public"."message" to "authenticated";

grant insert on table "public"."message" to "authenticated";

grant references on table "public"."message" to "authenticated";

grant select on table "public"."message" to "authenticated";

grant trigger on table "public"."message" to "authenticated";

grant truncate on table "public"."message" to "authenticated";

grant update on table "public"."message" to "authenticated";

grant delete on table "public"."message" to "service_role";

grant insert on table "public"."message" to "service_role";

grant references on table "public"."message" to "service_role";

grant select on table "public"."message" to "service_role";

grant trigger on table "public"."message" to "service_role";

grant truncate on table "public"."message" to "service_role";

grant update on table "public"."message" to "service_role";

grant delete on table "public"."message_session" to "anon";

grant insert on table "public"."message_session" to "anon";

grant references on table "public"."message_session" to "anon";

grant select on table "public"."message_session" to "anon";

grant trigger on table "public"."message_session" to "anon";

grant truncate on table "public"."message_session" to "anon";

grant update on table "public"."message_session" to "anon";

grant delete on table "public"."message_session" to "authenticated";

grant insert on table "public"."message_session" to "authenticated";

grant references on table "public"."message_session" to "authenticated";

grant select on table "public"."message_session" to "authenticated";

grant trigger on table "public"."message_session" to "authenticated";

grant truncate on table "public"."message_session" to "authenticated";

grant update on table "public"."message_session" to "authenticated";

grant delete on table "public"."message_session" to "service_role";

grant insert on table "public"."message_session" to "service_role";

grant references on table "public"."message_session" to "service_role";

grant select on table "public"."message_session" to "service_role";

grant trigger on table "public"."message_session" to "service_role";

grant truncate on table "public"."message_session" to "service_role";

grant update on table "public"."message_session" to "service_role";

grant delete on table "public"."message_session_users" to "anon";

grant insert on table "public"."message_session_users" to "anon";

grant references on table "public"."message_session_users" to "anon";

grant select on table "public"."message_session_users" to "anon";

grant trigger on table "public"."message_session_users" to "anon";

grant truncate on table "public"."message_session_users" to "anon";

grant update on table "public"."message_session_users" to "anon";

grant delete on table "public"."message_session_users" to "authenticated";

grant insert on table "public"."message_session_users" to "authenticated";

grant references on table "public"."message_session_users" to "authenticated";

grant select on table "public"."message_session_users" to "authenticated";

grant trigger on table "public"."message_session_users" to "authenticated";

grant truncate on table "public"."message_session_users" to "authenticated";

grant update on table "public"."message_session_users" to "authenticated";

grant delete on table "public"."message_session_users" to "service_role";

grant insert on table "public"."message_session_users" to "service_role";

grant references on table "public"."message_session_users" to "service_role";

grant select on table "public"."message_session_users" to "service_role";

grant trigger on table "public"."message_session_users" to "service_role";

grant truncate on table "public"."message_session_users" to "service_role";

grant update on table "public"."message_session_users" to "service_role";

grant delete on table "public"."organization" to "anon";

grant insert on table "public"."organization" to "anon";

grant references on table "public"."organization" to "anon";

grant select on table "public"."organization" to "anon";

grant trigger on table "public"."organization" to "anon";

grant truncate on table "public"."organization" to "anon";

grant update on table "public"."organization" to "anon";

grant delete on table "public"."organization" to "authenticated";

grant insert on table "public"."organization" to "authenticated";

grant references on table "public"."organization" to "authenticated";

grant select on table "public"."organization" to "authenticated";

grant trigger on table "public"."organization" to "authenticated";

grant truncate on table "public"."organization" to "authenticated";

grant update on table "public"."organization" to "authenticated";

grant delete on table "public"."organization" to "service_role";

grant insert on table "public"."organization" to "service_role";

grant references on table "public"."organization" to "service_role";

grant select on table "public"."organization" to "service_role";

grant trigger on table "public"."organization" to "service_role";

grant truncate on table "public"."organization" to "service_role";

grant update on table "public"."organization" to "service_role";

grant delete on table "public"."organization_members" to "anon";

grant insert on table "public"."organization_members" to "anon";

grant references on table "public"."organization_members" to "anon";

grant select on table "public"."organization_members" to "anon";

grant trigger on table "public"."organization_members" to "anon";

grant truncate on table "public"."organization_members" to "anon";

grant update on table "public"."organization_members" to "anon";

grant delete on table "public"."organization_members" to "authenticated";

grant insert on table "public"."organization_members" to "authenticated";

grant references on table "public"."organization_members" to "authenticated";

grant select on table "public"."organization_members" to "authenticated";

grant trigger on table "public"."organization_members" to "authenticated";

grant truncate on table "public"."organization_members" to "authenticated";

grant update on table "public"."organization_members" to "authenticated";

grant delete on table "public"."organization_members" to "service_role";

grant insert on table "public"."organization_members" to "service_role";

grant references on table "public"."organization_members" to "service_role";

grant select on table "public"."organization_members" to "service_role";

grant trigger on table "public"."organization_members" to "service_role";

grant truncate on table "public"."organization_members" to "service_role";

grant update on table "public"."organization_members" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();

CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger();

CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger();

CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger();

CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger();


